baseURL = 'https://shai0a.github.io/'
publishDir = 'docs'
languageCode = 'en-us'
title = 'My Page'
theme = 'm10c'

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[params]
description = "My personal page"

[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/shai0a"

[[params.social]]
  icon = "gitlab"
  name = "My GitLab"
  url = "https://gitlab.com/users/rfz0/projects"

